### ISSUE TITLE
Wikidata ID missing in author info

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#201]
In the current staging instance, Wikidata IDs for authors seem to be missing (tested on Firefox and Chrome), is this a regression?

![gryphius-regression](https://user-images.githubusercontent.com/6539515/127839449-9505ad6b-64f5-4e99-a366-378742974336.png)

**Comment by cmil** [comment]
This is caused by the (only half accidental) removal of the `key` property in dracor-org/dracor-api#151 (see https://github.com/dracor-org/dracor-api/pull/151/files#r680907651). 

Background: The single `key` attribute on `<author>` elements in the TEI has been superseded by potentially multiple `<idno>` elements inside `<author>` which translate to a `author.refs` array in the JSON output. This makes the `author.key` property obsolete, which is why I dropped it in the above mentioned PR. However, I didn't realise that the frontend still relies on the `key` property in several places. So the quick fix is to revert its removal. But we should still clean up the codebase so that the obsolete property can be removed at a later point.

**Comment by lehkost** [comment]
The ```key``` attribute was also just removed from our ```schema.rng```, so we shouldn't rely on it anywhere. ```key``` attributes were also removed from all corpora, IDs went to the ```idno``` element (type="wikidata" for Wikidata QIDs). While we can story different idno types in the documents (like "pnd", "bnf", "isni", etc.), we also decided to only use and show Wikidata IDs on the website.

**Comment by markschwindt** [comment]
While working on #108, I've noticed that Wikidata Author ID is now missing in corpora indices.

**Comment by cmil** [comment]
@markschwindt the above fix is now on staging.
